### ISSUE TITLE
Reladomo 16.7 support

### ISSUE THREAD

**Issue by seratch** [folio-sec/reladomo-scala#21]
Reladomo 16.7.0 has been released. :tada:

https://github.com/goldmansachs/reladomo/releases/tag/16.7.0

- [x] Cut off `reladomo-16.6.x` branch from the latest revision
- [x] Modify `master` branch to depend on reladomo 16.7

<img width="338" src="https://user-images.githubusercontent.com/19658/36057974-c83c9c08-0e59-11e8-88d3-3d47c136d791.png">

**Comment by matsu-chara** [comment]
released https://github.com/folio-sec/reladomo-scala/releases/tag/v16.7.0 :tada:
