### ISSUE TITLE
Cutting off `reladomo-16.5.x` branch for maintaining reladomo 16.5.x series

### ISSUE THREAD

**Issue by seratch** [folio-sec/reladomo-scala#5]
@itohiro73 

Reladomo 16.6.x is already available. I would like to update the `master` branch to depend on Reladomo 16.6.1, and we should have a new release.

To keep supporting Reladomo 16.5.x releases, I would like to cut off a branch named `reladomo-16.5.x` from the latest commit on `master` branch. We will mainly merge backport changes into the branch.

Currently, I don't have the permission to cut off a branch on this repository. Could you work on the branch creation or add me one of the collaborators having the permission? The operation will regularly happen from now on.

**Comment by itohiro73** [comment]
Thanks @seratch , I've created the branch.

I also added yo to the collaborators but not sure if the permission is sufficient. Could you please check?

**Comment by seratch** [comment]
Thank you for your prompt response. Yes, now I can create branches on this repository. (I don't still have the permission to make branches protected. Please do it when you have time)
