### ISSUE TITLE
Support BigDecimal as javaType

### ISSUE THREAD

**Issue by tkawachi** [folio-sec/reladomo-scala#9]
I tried `BigDecimal` as `javaType` of `<Attribute>`. A generated Java code seems good, but generated Scala code is using `String` instead of `BigDecimal`.

**Comment by seratch** [comment]
As the first step, we've implemented these types support: https://github.com/goldmansachs/reladomo-kata/blob/master/main-kata/src/main/reladomoxml/AllTypes.xml

Adding more types is quite easy. `BigDecimal` should be supported, too.
